# docs: https://espanso.org/docs/
global_vars:
  - name: "myname"
    type: "echo"
    params:
      echo: "Oleksii Luchnikov"

  - name: templater_path
    type: "echo"
    params:
      echo: "$VAULT_meta/template/"

matches:
  - trigger: ":me"
    replace: "{{myname}}"
  
  - trigger: "todo"
    replace: "TODO"

  - trigger: ":time"
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "%H:%M:%S"

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":uuid"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "uuidgen | tr A-F a-f | tr -d '-'"

  - trigger: ":rname"
    replace: "(?P<$|$>exp)"

  - trigger: "t:project"
    replace: "(?P<$|$>exp)"

  - trigger: "[["
    replace: "[[$|$"

  - trigger: ":t"
    force_clipboard: true
    replace: "{{output}}{{execute_templater}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - bash
            - "%CONFIG%/scripts/script.sh"
      - name: "execute_templater"
        type: "shell"
        params:
          cmd: "open --background 'obsidian://advanced-uri?vault=knowledge&commandid=templater-obsidian%3Areplace-in-file-templater'"

  - trigger: ":et"
    replace: "{{execute_templater}}"
    vars:
      - name: "execute_templater"
        type: "shell"
        params:
          cmd: "open 'obsidian://advanced-uri?vault=knowledge&commandid=templater-obsidian%3Areplace-in-file-templater'"

  - trigger: ":qmk"
    replace: "{{execute_templater}}"
    vars:
      - name: "execute_templater"
        type: "shell"
        params:
          cmd: "qmk compile -kb idobao/id75/v2 -km oleksiiluchnikov"